#### PYTHON FOR DATA ANALYTICS AND BUSINESS INTELLIGENCE

#### E-COMMERCE PURCHASE ANALYTICS

###### Import Libraries and Dependencies

In [1]:
import numpy as np
import pandas as pd

**Load the Dataset**

In [2]:
data_path = ".\data\EcommercePurchasesDataset"

ecommerce_data = pd.read_csv(data_path)
ecommerce_data.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

##### ANALYSIS OF THE DATASET USING FRAMED QUESTIONS

In [3]:
# Make a copy of the data, a good practice to avoid modifying the original data
data = ecommerce_data.copy()

**1. `Displaying the top 10 rows of the dataset`**

In [4]:
data.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

**2. `Displaying the last 10 rows of the dataset`**

In [5]:
data.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

**3, `Check the datatype of each column in the dataset`**

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  str
 1   Lot               10000 non-null  str
 2   AM or PM          10000 non-null  str
 3   Browser Info      10000 non-null  str
 4   Company           10000 non-null  str
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  str
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  str
 9   Email             10000 non-null  str
 10  Job               10000 non-null  str
 11  IP Address        10000 non-null  str
 12  Language          10000 non-null  str
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), str(11)
memory usage: 1.1 MB

In [7]:
data.dtypes

Address                 str
Lot                     str
AM or PM                str
Browser Info            str
Company                 str
Credit Card           int64
CC Exp Date             str
CC Security Code      int64
CC Provider             str
Email                   str
Job                     str
IP Address              str
Language                str
Purchase Price      float64
dtype: object

**4. `Checking for Null or Missing Values in the dataset`**

In [8]:
data.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

**5. `How many rows and columns are there in the dataset?`**

In [9]:
data.shape

(10000, 14)

In [10]:
print(f"There are {data.shape[0]} rows and {data.shape[1]} columns in the dataset.")

There are 10000 rows and 14 columns in the dataset.

In [11]:
print(f"The number of columns in the dataset is: {len(data.columns)}")
print(f"The number of rows in the dataset is: {len(data)}")

The number of columns in the dataset is: 14
The number of rows in the dataset is: 10000

**6. `What is the Highst and Lowest Purchase Price?`**

In [12]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [13]:
print(f"The Highest Purchase Price is {data['Purchase Price'].max()}.")
print(f"The Lowest Purchase Price is {data['Purchase Price'].min()}.")

The Highest Purchase Price is 99.99.
The Lowest Purchase Price is 0.0.

**7. `What is the Average Purchase Price?`**

In [14]:
print(f"The Average Purchase Price is {data['Purchase Price'].mean()}.")

The Average Purchase Price is 50.347302.

**8. `How many people speak french as a language?.`**

In [15]:
list(data.columns)

['Address',
 'Lot',
 'AM or PM',
 'Browser Info',
 'Company',
 'Credit Card',
 'CC Exp Date',
 'CC Security Code',
 'CC Provider',
 'Email',
 'Job',
 'IP Address',
 'Language',
 'Purchase Price']

In [16]:
data["Language"].value_counts()

Language
de    1155
ru    1155
el    1137
pt    1118
en    1098
fr    1097
es    1095
it    1086
zh    1059
Name: count, dtype: int64

In [17]:
len(data[data["Language"] == "fr"])

1097

In [18]:
data[data["Language"] == "fr"].count()

Address             1097
Lot                 1097
AM or PM            1097
Browser Info        1097
Company             1097
Credit Card         1097
CC Exp Date         1097
CC Security Code    1097
CC Provider         1097
Email               1097
Job                 1097
IP Address          1097
Language            1097
Purchase Price      1097
dtype: int64

In [19]:
print(f"The number of people who speak French as their language is {len(data[data['Language'] == 'fr'])} people.")

The number of people who speak French as their language is 1097 people.

**9. `How many people has the job title that contains Engineer?`**

In [20]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [21]:
# FUNCTION TO CHECK IF THE JOB TITLE CONTAINS THE WORD "ENGINEER"
def contain_engineer(string):
    if "engineer" in string.lower():
        return string
    else:
        pass

In [22]:
data["Job"].apply(contain_engineer)

0                     NaN
1       Drilling engineer
2                     NaN
3       Drilling engineer
4                     NaN
              ...
9995                  NaN
9996      Energy engineer
9997                  NaN
9998                  NaN
9999                  NaN
Name: Job, Length: 10000, dtype: str

In [23]:
# DROPPING THE NULL VALUES
data["Job"].apply(contain_engineer).dropna()

1                         Drilling engineer
3                         Drilling engineer
50                      Mechanical engineer
55      Engineer, broadcasting (operations)
60                   Engineer, agricultural
                       ...
9948                    Structural engineer
9952                       Engineer, energy
9970                    Electrical engineer
9977                    Biomedical engineer
9996                        Energy engineer
Name: Job, Length: 984, dtype: str

In [24]:
# NOW COUNT THE NUMBER OF ENGINEERS IN THE DATASET USING THE len() FUNCTION
len(data["Job"].apply(contain_engineer).dropna())

984

In [25]:
print(f"The number of people with the word 'engineer' in their job title is {len(data['Job'].apply(contain_engineer).dropna())} people.")

The number of people with the word 'engineer' in their job title is 984 people.

In [26]:
# ALTERNATIVELY, WE CAN USE THE STR.CONTAINS() METHOD TO CHECK IF THE JOB TITLE CONTAINS THE WORD "ENGINEER" AND THEN COUNT THE NUMBER OF TRUE VALUES
len(data[data["Job"].str.contains("engineer", case=False, na=False)])

984

**10. `How many job title actually contains engineer?`**

In [27]:
print(f"The job title that actually contains the word 'engineer' is {data['Job'].apply(contain_engineer).dropna().nunique()} unique engineer job titles.")

The job title that actually contains the word 'engineer' is 61 unique engineer job titles.

**11. `Find the email of the person with the following IP address: 121.133.168.51`**

In [28]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [29]:
data[data["IP Address"] == "121.133.168.51"][["Email"]]

                   Email
9996  mary85@hotmail.com

In [30]:
data[data["IP Address"] == "121.133.168.51"]["Email"]

9996    mary85@hotmail.com
Name: Email, dtype: str

In [31]:
print(f"The email of the person with the IP address '121.133.168.51' is: {data[data['IP Address'] == '121.133.168.51']['Email'].iloc[0]}.")

The email of the person with the IP address '121.133.168.51' is: mary85@hotmail.com.

**12. `How many people have MasterCard as their Credit Card Provider and made a Purchase above 50?`**

In [32]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [33]:
len(data[(data["CC Provider"] == "Mastercard") & (data["Purchase Price"] > 50)])

405

In [34]:
print(f"The number of people who has Mastercard as their credit card provider and made a purchase above 50 is {len(data[(data['CC Provider'] == 'Mastercard') & (data['Purchase Price'] > 50)])} people.")

The number of people who has Mastercard as their credit card provider and made a purchase above 50 is 405 people.

In [35]:
data[(data["CC Provider"] == "Mastercard") & (data["Purchase Price"] > 50)].count()

Address             405
Lot                 405
AM or PM            405
Browser Info        405
Company             405
Credit Card         405
CC Exp Date         405
CC Security Code    405
CC Provider         405
Email               405
Job                 405
IP Address          405
Language            405
Purchase Price      405
dtype: int64

**13. `Find the email of the person with the following Credit Card Number: 6011539787356311`**

In [36]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [37]:
data[data["Credit Card"] == 6011539787356311]['Email']
print(f"The email with the Credit Card Number: 6011539787356311 is: {data[data['Credit Card'] == 6011539787356311]['Email'].iloc[0]}.")

The email with the Credit Card Number: 6011539787356311 is: tyler16@gmail.com.

**14. `How many people purchase during the morning (AM) and how many people purchase during the afternoon (PM)?`**

In [38]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [39]:
data["AM or PM"].unique()

<StringArray>
['PM', 'AM']
Length: 2, dtype: str

In [40]:
len(data[data["AM or PM"] == "AM"]["Purchase Price"])

4932

In [41]:
print(f"People who made purchase in the morning are: {len(data[data['AM or PM'] == 'AM']['Purchase Price'])}")

People who made purchase in the morning are: 4932

In [42]:
print(f"People who made purchase in the afternoon are: {len(data[data['AM or PM'] == 'PM']['Purchase Price'])}")

People who made purchase in the afternoon are: 5068

In [43]:
# OR WE CAN SIMPLY USE THE VALUE_COUNTS() METHOD

data["AM or PM"].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

**15. `How many people have a Credit Card that expires in 2020?`**

In [44]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [45]:
data["CC Exp Date"]

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: str

###### **because of the expiry date type 02/20..02/19, we would need to split by `/` to access the year which is a second value in this dataset.**

In [46]:
data["CC Exp Date"].str.split("/")

0       [02, 20]
1       [11, 18]
2       [08, 19]
3       [02, 24]
4       [10, 25]
          ...
9995    [03, 22]
9996    [07, 25]
9997    [05, 21]
9998    [11, 17]
9999    [02, 19]
Name: CC Exp Date, Length: 10000, dtype: object

###### **Write a function to perform the splitting and extract the second item in the list `[02, 20]` using indexing, here `02` is indexed `0` and `20` is indexed `1`**

In [47]:
def date_splitter(date_string):
    return date_string.split("/")[1]

In [48]:
data["CC Exp Date"].apply(date_splitter)

0       20
1       18
2       19
3       24
4       25
        ..
9995    22
9996    25
9997    21
9998    17
9999    19
Name: CC Exp Date, Length: 10000, dtype: str

In [49]:
data["CC Exp Date"].apply(date_splitter) == "20"

0        True
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: CC Exp Date, Length: 10000, dtype: bool

In [50]:
len(data[data["CC Exp Date"].apply(date_splitter) == "20"])

print(f"The number of people whose credit card expires in 2020 is: {len(data[data['CC Exp Date'].apply(date_splitter) == '20'])}.")

The number of people whose credit card expires in 2020 is: 988.

##### **USING THE ANONYMOUS LAMBDA FUNCTION**

In [51]:
data["CC Exp Date"].apply(lambda date_string: date_string.split("/")[1] == "20")

0        True
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: CC Exp Date, Length: 10000, dtype: bool

In [52]:
len(data[data["CC Exp Date"].apply(lambda date_string: date_string.split("/")[1] == "20")])

988

##### **A MORE COMPACTED FUNCTION AND PRINT THE RESULT AT ONCE**

In [53]:
def date_splitter_and_counter():
    counter = 0
    for date_string in data["CC Exp Date"]:
        if date_string.split("/")[1] == "20":
            counter = counter + 1
    
    print("The number of people whose credit card expires in 2020 is: ", counter)

In [54]:
date_splitter_and_counter()

The number of people whose credit card expires in 2020 is:  988

**16. `The top 5 most popular email providers with domain name such as gmail.com, yahoo.com, etc`**

In [55]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [56]:
data["Email"]

0                    pdunlap@yahoo.com
1                   anthony41@reed.com
2       amymiller@morales-harrison.com
3          brent16@olson-robinson.info
4          christopherwright@gmail.com
                     ...
9995            iscott@wade-garner.com
9996                mary85@hotmail.com
9997                 tyler16@gmail.com
9998           elizabethmoore@reid.net
9999             rachelford@vaughn.com
Name: Email, Length: 10000, dtype: str

###### **We would need to extract the email domian name from each email by splitting and accessing the second value**

In [57]:
data['Email'].str.split('@')

0                    [pdunlap, yahoo.com]
1                   [anthony41, reed.com]
2       [amymiller, morales-harrison.com]
3          [brent16, olson-robinson.info]
4          [christopherwright, gmail.com]
                      ...
9995            [iscott, wade-garner.com]
9996                [mary85, hotmail.com]
9997                 [tyler16, gmail.com]
9998           [elizabethmoore, reid.net]
9999             [rachelford, vaughn.com]
Name: Email, Length: 10000, dtype: object

In [58]:
list_of_email_providers = []

for domain_name in data['Email']:
    split = domain_name.split('@')[1]
    list_of_email_providers.append(split)

In [59]:
list_of_email_providers[:4]

['yahoo.com', 'reed.com', 'morales-harrison.com', 'olson-robinson.info']

###### **Create a temporary column for the email providers in the data**

In [60]:
data['Email Providers'] = list_of_email_providers

data.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,Email Providers
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,reed.com

###### **Then use value_counts() to diplay the top 5**

In [61]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price', 'Email Providers'],
      dtype='str')

In [62]:
top_5_email_providers = data['Email Providers'].value_counts().head()

In [63]:
print("The top 5 Email Providers are: \n", top_5_email_providers)

The top 5 Email Providers are:
 Email Providers
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

##### **USING THE ANONYMOUS LAMBDA FUNCTION FOR THE SAME TASK**

In [64]:
data['Email'].apply(lambda email: email.split('@')[1])

0                  yahoo.com
1                   reed.com
2       morales-harrison.com
3        olson-robinson.info
4                  gmail.com
                ...
9995         wade-garner.com
9996             hotmail.com
9997               gmail.com
9998                reid.net
9999              vaughn.com
Name: Email, Length: 10000, dtype: str

In [65]:
data['Email'].apply(lambda email: email.split('@')[1]).value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

#### **THE END OF PROJECT 2**