##### PYTHON FOR DATA ANALYTICS SYNTHETIC PRACTICES

##### Import Libraries and Dependencies

In [1]:
import numpy as np
import pandas as pd

In [2]:
StudentData = {
    "Name": ["Olanrewaju", "Adebisi", "Esther", "Hannah", "Adegoke", "Adeshina", "Owolabi"],
    "Scores": [98, 95, 94, 93, 70, 85, 83],
    "Gender": ["Male", "Female", "Female", "Female", "Male", "Male", "Male"]
}

data = pd.DataFrame(StudentData)
data

         Name  Scores  Gender
0  Olanrewaju      98    Male
1     Adebisi      95  Female
2      Esther      94  Female
3      Hannah      93  Female
4     Adegoke      70    Male
5    Adeshina      85    Male
6     Owolabi      83    Male

**With the above information, we shall build synthetic data analytics procedures using questions with solutions to explain each steps**

**1. `Display the top 2 rows in the dataset`**

In [3]:
data.head(2)

         Name  Scores  Gender
0  Olanrewaju      98    Male
1     Adebisi      95  Female

**2. `Display the last 2 rows in the dataset`**

In [4]:
data.tail(2)

       Name  Scores Gender
5  Adeshina      85   Male
6   Owolabi      83   Male

**3. `Find the shape of the dataset (Number of rows and Number of columns)`**

In [5]:
data.shape

(7, 3)

In [6]:
print(f"Number of Rows: {data.shape[0]}")
print(f"Number of Columns: {data.shape[1]}")

Number of Rows: 7
Number of Columns: 3

**4. `Obtain the information about the dataset (Total Number of Rows and Columns, Datatypes of each column and Memory Requirements)`**

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Scores  7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

**5. `Check for Null or Missing Values in the dataset`**

In [8]:
data.isnull()

    Name  Scores  Gender
0  False   False   False
1  False   False   False
2  False   False   False
3  False   False   False
4  False   False   False
5  False   False   False
6  False   False   False

In [9]:
data.isnull().values.any()

np.False_

In [10]:
data.isnull().sum()

Name      0
Scores    0
Gender    0
dtype: int64

In [11]:
data.isnull().sum(axis=0)

Name      0
Scores    0
Gender    0
dtype: int64

In [12]:
data.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

**6. `Get the Overall Statistics About the DataFrame`**

In [13]:
data.describe()

          Scores
count   7.000000
mean   88.285714
std     9.724784
min    70.000000
25%    84.000000
50%    93.000000
75%    94.500000
max    98.000000

In [14]:
data.describe(include="all")

              Name     Scores Gender
count            7   7.000000      7
unique           7        NaN      2
top     Olanrewaju        NaN   Male
freq             1        NaN      4
mean           NaN  88.285714    NaN
std            NaN   9.724784    NaN
min            NaN  70.000000    NaN
25%            NaN  84.000000    NaN
50%            NaN  93.000000    NaN
75%            NaN  94.500000    NaN
max            NaN  98.000000    NaN

**7. `Find the Unique Values from the Gender Column`**

In [15]:
data["Gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

**8. `Find the number of Unique Values from the Gender Column`**

In [16]:
data["Gender"].nunique()

2

**9. `Display the count of Unique Values in Gender Column`**

In [17]:
data["Gender"].value_counts()

Gender
Male      4
Female    3
Name: count, dtype: int64

**10. `Find the total number of students scoring between 90 to 100 (inclusive) using between method`**