##### **CUSTOMER SHOPPING BEHAVIOUR ANALYSIS** #####

###### *IMPORT DEPENDENCIES AND LIBRARIES*

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

###### *Loading the dataset*

In [2]:
data_path = "./data/customer_shopping_behavior.csv"

customer_data = pd.read_csv(data_path)

customer_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

###### **EDA**

In [3]:
df = customer_data.copy()

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [5]:
print(f"There are {df.shape[0]} rows and {df.shape[1]} columns in the dataset.")

There are 3900 rows and 18 columns in the dataset.

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,NaN,NaN,NaN,1950.5,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,NaN,NaN,NaN,44.068462,15.207589,18.0,31.0,44.0,57.0,70.0
Gender,3900,2,Male,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Item Purchased,3900,25,Blouse,171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,3900,4,Clothing,1737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase Amount (USD),3900.0,NaN,NaN,NaN,59.764359,23.685392,20.0,39.0,60.0,81.0,100.0
Location,3900,50,Montana,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,3900,4,M,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Color,3900,25,Olive,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Season,3900,4,Spring,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review Rating,3863.0,NaN,NaN,NaN,3.750065,0.716983,2.5,3.1,3.8,4.4,5.0
Subscription Status,3900,2,No,2847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shipping Type,3900,6,Free Shipping,675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount Applied,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Promo Code Used,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Previous Purchases,3900.0,NaN,NaN,NaN,25.351538,14.447125,1.0,13.0,25.0,38.0,50.0
Payment Method,3900,6,PayPal,677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Frequency of Purchases,3900,7,Every 3 Months,584,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###### **`Check the Missing Values`**

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df.isnull().sum(axis=0)

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df.isnull().sum(axis=1)

0       0
1       0
2       0
3       0
4       0
       ..
3895    0
3896    0
3897    0
3898    0
3899    0
Length: 3900, dtype: int64

In [11]:
df["Category"].unique()

<StringArray>
['Clothing', 'Footwear', 'Outerwear', 'Accessories']
Length: 4, dtype: str

###### *There are missing values in the dataset for the `review rating column` howbeit, this missing values can be computed using `mean or median` but it is worth to know that the `mean` is proned to outliers hence may not be the best metric to use for correcting the missing values instead the `median` would be the best option here but here is another point to watch out for, this rating is for different categories hence using `median` or `mean` to as a single replacement across the entire dataset may introduce biases, hence the best approach is to compute the `median` for each categories and use it to replace it.*

In [12]:
df.groupby('Category')['Review Rating'].transform(lambda category: category.fillna(category.median()))

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [13]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda category: category.fillna(category.median()))

In [14]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

###### **Change the column names to something uniform by using the snake case type**

In [15]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [16]:
# convert the column names into lower case

df.columns = df.columns.str.lower()

df.columns

Index(['customer id', 'age', 'gender', 'item purchased', 'category',
       'purchase amount (usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchases',
       'payment method', 'frequency of purchases'],
      dtype='str')

In [17]:
# replace empty space with underscore

df.columns = df.columns.str.replace(" ", "_")

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [18]:
df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'}).head(2)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly

In [19]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

#### **Feature Engineering**

In [20]:
df.head(2)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly

###### **`Create another column with the age called the age_group - ['Young Adult', 'Adult', 'Middle Aged', 'Senior']`**

In [21]:
labels = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']

df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [22]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle Aged
1   19  Young Adult
2   50  Middle Aged
3   21  Young Adult
4   45  Middle Aged
5   46  Middle Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle Aged

###### **`Create another column for purchase_frequency_days using frequency_of_purchases`**

In [23]:
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [24]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

In [25]:
df['freq_of_purchases_in_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [26]:
df[['frequency_of_purchases', 'freq_of_purchases_in_days']].head(10)

  frequency_of_purchases  freq_of_purchases_in_days
0            Fortnightly                         14
1            Fortnightly                         14
2                 Weekly                          7
3                 Weekly                          7
4               Annually                        365
5                 Weekly                          7
6              Quarterly                         90
7                 Weekly                          7
8               Annually                        365
9              Quarterly                         90

###### **`Removing redundant columns`**

In [27]:
list(df.columns)

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'promo_code_used',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases',
 'age_group',
 'freq_of_purchases_in_days']

In [28]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [29]:
# To check if they contains the same items across all the rows

(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [30]:
# drop the promo_code_used
df = df.drop('promo_code_used', axis=1)

In [31]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,freq_of_purchases_in_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Aged,365

##### **MOVE THE DATASET TO THE POSTGRESS SQL DATABASE FOR ONWARD ANALYSIS**

In [32]:
# !pip install psycopg2-binary sqlalchemy
# pip install psycopg2-binary sqlalchemy

In [33]:
# # Importing library
# from sqlalchemy import create_engine

# # Step 1: Connecting to PostgreSQL and Replacing all placeholders with your actual credentials

# username = "postgre"         # default user
# password = "your_password"   # the password you set for your postgreSQL during installation
# host = "localhost"           # if running locally
# port = "5432"                # default PostgreSQL port
# database = "your_database_created"         # the database you created for the project in the pgAdmin

# engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# # Step 2: Load the DataFrame into PostgreSQL

# table_name = "customer"     # choose any table name

# dataframe.to_sql(table_name, engine, if_exists="replace", index=False)

# print(f"Data successfully loaded into the data table name: {table_name} in the database: {database}")

##### **MOVE THE DATASET TO THE MySQL DATABASE FOR ONWARD ANALYSIS**

In [35]:
!pip install pymysql sqlalchemy
#pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.3.2-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\olanrewaju adegoke\python_for_data_analysis\data_analysis_venv\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.3 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.3 kB ? eta -:--:--
   --------------------------- ------------ 30.7/45.3 kB 330.3 kB/s eta 0:00:01
   ---------------------------------------- 45.3/45.3 kB 377.0 kB/s eta 0:00:00
Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------- -------------------------------- 0.4/2.1 MB 8.7 MB/s eta 0:00:01
   ---------------------- ----------------- 1.2/2.1 MB 12.7 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 17.0 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 17.0 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 11.3 MB/s eta 0:00:00
Using cached greenlet-3.3.2-cp311-cp311-win_amd64.whl (230 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy
Successfully installed greenlet-3.3.2 pymysql-1.1.2 sqlalchemy-2.0.48

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\olanrewaju adegoke\python_for_data_analysis\data_analysis_venv\lib\site-packages (1.2.2)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
from dotenv import load_dotenv
import os

In [40]:
# Loads the .env into the environment variables

load_dotenv()

# Importing library
from sqlalchemy import create_engine

# Step 1: Connecting to MySQL and Replacing all placeholders with your actual credentials

username = os.getenv("DB_USER")         # default user
password = os.getenv("DB_PASSWORD")   # the password you set for your MySQL during installation
host = os.getenv("DB_HOST")           # if running locally
port = os.getenv("DB_PORT")                # default MySQL port
database = os.getenv("DB_NAME")         # the database you created for the project

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load the DataFrame into MySQL

table_name = "customer"     # choose any table name

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into the data table name: {table_name} in the database: {database}")

# Step 3: Read the data to the notebook from the MySQL database
pd.read_sql(f"SELECT * FROM {table_name} LIMIT 10;", engine)

Data successfully loaded into the data table name: customer in the database: customer_shopping_db

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,freq_of_purchases_in_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Aged,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle Aged,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle Aged,90

##### **MOVE THE DATASET TO THE MS SQL SERVER DATABASE FOR ONWARD ANALYSIS**

In [ ]:
# !pip install pyodbc sqlalchemy
# pip install pyodbc sqlalchemy

In [ ]:
# # Importing library
# from sqlalchemy import create_engine
# from urllib.parse import quote_plus

# # Step 1: Connecting to MS SQL SERVER and Replacing all placeholders with your actual credentials

# username = "sa"         # default user
# password = "your_password"   # the password you set for your MS SQL Server during installation
# host = "localhost"           # if running locally
# port = "1433"                # default MS SQL Server port
# database = "customer_shopping_db"         # the database you created for the project

# # Note: This requires that Microsoft ODBC Driver is installed separately on the system
# driver = quote_plus("ODBC Driver 17 for SQL Server")
# engine = create_engine(f"mssql+pyodbc://{username}:{password}@{host},{port}/{database}?driver={driver}")

# # Step 2: Load the DataFrame into MS SQL

# table_name = "customer"     # choose any table name

# dataframe.to_sql(table_name, engine, if_exists="replace", index=False)

# print(f"Data successfully loaded into the data table name: {table_name} in the database: {database}")

# # Step 3: Read the data to the notebook from the MySQL database
# pd.read_sql(f"SELECT TOP 10 * FROM {table_name};", engine)

###### PROCEED to MySQL WORKBENCH FOR BUSINESS ANALYSIS USING SQL