##### **PYTHON FOR DATA ANALYTICS AND BUSINESS INTELLIGENCE**

##### **EMPLOYEE SALARIES ANALYTICS**

###### *Import the Libraries and Dependencies*

In [1]:
import numpy as np
import pandas as pd

###### *Load the dataset*

In [2]:
data_path = "./data/employee_salaries.csv"
salary_data = pd.read_csv(data_path, low_memory=False)
salary_data.head(2)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN

In [3]:
data = salary_data.copy()

**1. `Display the top 10 rows of the dataset`**

In [4]:
print("The top 10 rows in the dataset are: \n")
data.head(10)

The top 10 rows in the dataset are:

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.0,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.0,51322.5,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

**2. `Check the last 10 rows of the dataset`**

In [5]:
print("The last 10 rows in the dataset are: \n")
data.tail(10)

The last 10 rows in the dataset are:

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

**3. `Find the shape of the dataset (number of rows and number of columns in the dataste)`**

In [6]:
print(f"There are {data.shape[0]} rows and {data.shape[1]} columns in the dataset.")

There are 148654 rows and 13 columns in the dataset.

**4. `Obtain the information about the dataset like total number of rows and columns, datatypes of each columns and the memort requirements`**

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148049 non-null  str
 4   OvertimePay       148654 non-null  str
 5   OtherPay          148654 non-null  str
 6   Benefits          112495 non-null  str
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 14.7 MB

In [8]:
data.dtypes

Id                    int64
EmployeeName            str
JobTitle                str
BasePay                 str
OvertimePay             str
OtherPay                str
Benefits                str
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency                  str
Status                  str
dtype: object

###### *We expect the following columns to be a float or int data types `['BasePay', 'OvertimePay', 'OtherPay', 'Benefits']` but they were all strings and we need to convert them back to float or int datatypes*

###### *CONVERT NUMERICAL COLUMNS IN DTYPE (STR) TO DTYPE (FLOAT64)*

In [9]:
COLS_TO_FLOAT = ['BasePay', 'OvertimePay', 'OtherPay', 'Benefits']
data[COLS_TO_FLOAT] = data[COLS_TO_FLOAT].apply(pd.to_numeric, errors='coerce').astype('float64')    # errors='coerce' converts invalid values to 'NaN'

data.dtypes

Id                    int64
EmployeeName            str
JobTitle                str
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency                  str
Status                  str
dtype: object

**5. `Check the null or missing values in the dataset`**

In [10]:
data.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [11]:
data.isnull().sum(axis=0)

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [12]:
data.isnull().sum(axis=1)

0         3
1         3
2         3
3         3
4         3
         ..
148649    1
148650    6
148651    6
148652    6
148653    1
Length: 148654, dtype: int64

**6. `Drop all irrelevant columns such as 'ID', 'Notes', 'Agency' and 'Status'`**

In [13]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [14]:
unwanted_columns = ['Id', 'Notes', 'Agency', 'Status']
data.drop(columns=unwanted_columns, inplace=True)
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

**7. `Obtain the overall descriptive statistics of the dataset`**

In [15]:
data.describe()

,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
mean,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

**8. `Find the top 10 occurence of the employee names`**

In [16]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [17]:
data['EmployeeName'].value_counts().head(10)

EmployeeName
Kevin Lee       13
Steven Lee      11
William Wong    11
Richard Lee     11
KEVIN LEE        9
Stanley Lee      9
Michael Wong     9
John Chan        9
MICHAEL LEE      8
RICHARD LEE      8
Name: count, dtype: int64

**9. `Find the number of uniquely Job titles`**

In [18]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [19]:
data['JobTitle'].unique()

<StringArray>
[  'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
                  'CAPTAIN III (POLICE DEPARTMENT)',
             'WIRE ROPE CABLE MAINTENANCE MECHANIC',
     'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',
                        'ASSISTANT DEPUTY CHIEF II',
               'BATTALION CHIEF, (FIRE DEPARTMENT)',
                   'DEPUTY DIRECTOR OF INVESTMENTS',
           'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
 'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
                      'EXECUTIVE CONTRACT EMPLOYEE',
 ...
                      'Hospital Eligibility Worker',
                                'Personnel Trainee',
                      'ACPO,JuvP, Juv Prob (SFERS)',
                        'Apprentice Cement Mason I',
                         'Marina Associate Manager',
                     'Sr Cnselor, Juv Hall (SFERS)',
                   'Forensic Toxicologist Supervis',
                                       'Conversion',
                                        'Cashier 3',
                                     'Not provided']
Length: 2159, dtype: str

###### **Note that `Not Provided` is not a Job Title but we are considering it because we have not corrected missing value or unrelated entries. In the future, it will be corrected using correcting missing value method for strings**

In [20]:
print(f"The number of uniquely identified job titles are: {data['JobTitle'].nunique()}.")

The number of uniquely identified job titles are: 2159.

**10. `The total number of Job Titles that contain Captain`**

In [21]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [22]:
data['JobTitle']

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: str

In [23]:
def extract_captain(strings):
    if 'captain' in strings.lower():
        return strings
    else:
        pass

In [24]:
data['JobTitle'].apply(extract_captain)

0                                     NaN
1         CAPTAIN III (POLICE DEPARTMENT)
2         CAPTAIN III (POLICE DEPARTMENT)
3                                     NaN
4                                     NaN
                       ...
148649                                NaN
148650                                NaN
148651                                NaN
148652                                NaN
148653                                NaN
Name: JobTitle, Length: 148654, dtype: str

In [25]:
# DROP THE NaN

data['JobTitle'].apply(extract_captain).dropna()

1               CAPTAIN III (POLICE DEPARTMENT)
2               CAPTAIN III (POLICE DEPARTMENT)
11              CAPTAIN III (POLICE DEPARTMENT)
17        CAPTAIN, EMERGENCYCY MEDICAL SERVICES
22                    CAPTAIN, FIRE SUPPRESSION
                          ...
116604                Captain, Fire Suppression
120867                                Captain 3
122361                Captain, Fire Suppression
126588                                Captain 3
132232                Captain, Fire Suppression
Name: JobTitle, Length: 552, dtype: str

In [26]:
# NOW COUNT THE NUMBER OF JOB TITTLE THAT CONTAIN CAPTAIN IN THE DATASET USING THE len() FUNCTION
len(data['JobTitle'].apply(extract_captain).dropna())

552

In [27]:
print(f"The number of Job Title with the word 'captain' in the job title is {len(data['JobTitle'].apply(extract_captain).dropna())}.")

The number of Job Title with the word 'captain' in the job title is 552.

In [28]:
# USING LAMBDA FUNCTION
len(data['JobTitle'].apply(lambda jobtitle: jobtitle if 'captain' in jobtitle.lower() else None ).dropna())

552

In [29]:
# USING THE CONTAIN METHOD

data['JobTitle'].str.contains('captain', case=False, na=False)

0         False
1          True
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [30]:
# PASSED UNTO THE DATAFRAME TO EXTRACT ONLY THE TRUE VALUES

data[data['JobTitle'].str.contains('captain', case=False, na=False)]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
116604,Gregory L Stewart,"Captain, Fire Suppression",73355.21,18517.18,49917.73,25608.77,141790.12,167398.89,2014
120867,Michael J Moran,Captain 3,7660.00,1496.09,126560.36,2189.51,135716.45,137905.96,2014
122361,Michael V Rolovich,"Captain, Fire Suppression",0.00,0.00,130320.75,0.00,130320.75,130320.75,2014
126588,Stephen M Tittel,Captain 3,68491.89,0.00,23721.91,19020.79,92213.80,111234.59,2014
132232,Jeanne M Seyler,"Captain, Fire Suppression",61039.43,2285.30,7548.29,20113.76,70873.02,90986.78,2014

In [31]:
len(data[data['JobTitle'].str.contains('captain', case=False, na=False)])

552

In [32]:
# BEST OPTION IF YOU STILL WANT TO MAINTAIN THE DATAFRAME SIZE AND INTEGRATE THE RESULT BACK INTO THE DATAFRAME
# data['filtered_job_title'] = data['JobTitle'].where(data['JobTitle'].str.contains('captain', case=False, na=False))
# len(data['filtered_job_title'].dropna())

**11. `Display all the employee names from the Fire Department`**

In [33]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

###### *Here, we would use the JobTitle to be able to search for the department with the keyword - `fire department` to be contained in the Job title*

In [34]:
data['JobTitle']

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: str

In [35]:
data[data['JobTitle'].str.contains('fire department', case=False, na=False)]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
6,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011
8,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011
9,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011
10,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999.39,71344.88,33149.90,NaN,299494.17,299494.17,2011
...,...,...,...,...,...,...,...,...,...
32623,JAMES BARDEN,"BATTALION CHIEF, (FIRE DEPARTMENT)",0.00,1290.69,5802.68,NaN,7093.37,7093.37,2011
36162,Joanne Hayes-White,"Chief, Fire Department",296943.01,0.00,17816.59,72047.88,314759.60,386807.48,2012
72926,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.00,23236.00,85431.39,336922.01,422353.40,2013
102303,Robert E Evans,"Captain, (Fire Department)",NaN,0.00,35332.78,0.00,35332.78,35332.78,2013
110535,Joanne M Hayes-White,"Chief, Fire Department",302068.00,0.00,24165.44,91201.66,326233.44,417435.10,2014

In [36]:
# all employee names from fire department

data[data['JobTitle'].str.contains('fire department', case=False, na=False)]['EmployeeName']

4              PATRICK GARDNER
6                    ALSON LEE
8               MICHAEL MORRIS
9           JOANNE HAYES-WHITE
10               ARTHUR KENNEY
                  ...
32623             JAMES BARDEN
36162       Joanne Hayes-White
72926     Joanne M Hayes-White
102303          Robert E Evans
110535    Joanne M Hayes-White
Name: EmployeeName, Length: 226, dtype: str

In [37]:
print("Number of Employees that worked at the fire department: ", len(data[data['JobTitle'].str.contains('fire department', case=False, na=False)]['EmployeeName']))

Number of Employees that worked at the fire department:  226

**12. `Find the minimum, maximum and average base pay`**

In [38]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [39]:
data['BasePay'].describe()

count    148045.000000
mean      66325.448840
std       42764.635495
min        -166.010000
25%       33588.200000
50%       65007.450000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64

In [40]:
print(f"The minimum base pay is: ${data['BasePay'].min():,.2f}")
print(f"The maximum base pay is: ${data['BasePay'].max():,.2f}")
print(f"The average base pay is: ${data['BasePay'].mean():,.2f}")

The minimum base pay is: $-166.01
The maximum base pay is: $319,275.01
The average base pay is: $66,325.45

In [41]:
# EUROPEAN CURRENCY FORMATTING

value = data['BasePay'].max()
EU_currency_format = f"€{value:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
print(EU_currency_format)

€319.275,01

In [42]:
base_min = data['BasePay'].min()
base_max = data['BasePay'].max()
base_avr = data['BasePay'].mean()

print(f"The minimum base pay is: €{f'{base_min:,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.')}")
print(f"The maximum base pay is: €{f'{base_max:,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.')}")
print(f"The average base pay is: €{f'{base_avr:,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.')}")

The minimum base pay is: €-166,01
The maximum base pay is: €319.275,01
The average base pay is: €66.325,45

**13. `Correct the 'Not Provided' in Employeename Column to 'NaN'`**

In [43]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [44]:
data["EmployeeName"]

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: str

In [45]:
data["EmployeeName"] = data["EmployeeName"].replace({'Not provided': np.nan})
# data["EmployeeName"] = data["EmployeeName"].replace('Not provided', np.nan)

data["EmployeeName"]

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650                  NaN
148651                  NaN
148652                  NaN
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: str

**14. `Drop the rows having 5 missing values`**

In [46]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [47]:
data.isnull().sum()

EmployeeName            4
JobTitle                0
BasePay               609
OvertimePay             4
OtherPay                4
Benefits            36163
TotalPay                0
TotalPayBenefits        0
Year                    0
dtype: int64

In [48]:
data.isnull().sum(axis=0) # To show columns

EmployeeName            4
JobTitle                0
BasePay               609
OvertimePay             4
OtherPay                4
Benefits            36163
TotalPay                0
TotalPayBenefits        0
Year                    0
dtype: int64

In [49]:
data.isnull().sum(axis=1)  # To show rows

0         1
1         1
2         1
3         1
4         1
         ..
148649    0
148650    5
148651    5
148652    5
148653    0
Length: 148654, dtype: int64

###### *We are interested i where the missing valueson the row is 5*

In [50]:
data.isnull().sum(axis=1) == 5

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650     True
148651     True
148652     True
148653    False
Length: 148654, dtype: bool

In [51]:
data[data.isnull().sum(axis=1) == 5]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
148646,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148650,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148651,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148652,NaN,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014

###### *We can then drop the filtered dataset from the dataframe*

In [52]:
data = data.drop(data[data.isnull().sum(axis=1) == 5].index, axis=0)
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148645,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014
148647,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014
148648,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

In [53]:
data[data.isnull().sum(axis=1) == 5]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [54]:
data.isnull().sum(axis=1)

0         1
1         1
2         1
3         1
4         1
         ..
148645    0
148647    0
148648    0
148649    0
148653    0
Length: 148650, dtype: int64

In [55]:
"""
# USE TO REPLACE ALL Not provided entries in the dataset
for col in salary_data.columns:
    salary_data[col] = salary_data[col].replace({'Not provided': np.nan})


# USE TO REPLACE ALL Not provided entries in the dataset
salary_data.replace('Not provided', np.nan, inplace=True)
"""

"\n# USE TO REPLACE ALL Not provided entries in the dataset\nfor col in salary_data.columns:\n    salary_data[col] = salary_data[col].replace({'Not provided': np.nan})\n\n\n# USE TO REPLACE ALL Not provided entries in the dataset\nsalary_data.replace('Not provided', np.nan, inplace=True)\n"

**15. `Find the Job Title of 'ALBERT PARDINI'`**

In [56]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [57]:
data['EmployeeName']

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148645     Carolyn A Wilson
148647       Joann Anderson
148648          Leon Walker
148649        Roy I Tillery
148653            Joe Lopez
Name: EmployeeName, Length: 148650, dtype: str

In [58]:
# TO CHECK IF THE NAME EXIST
data['EmployeeName'].apply(lambda x: x if x.lower() == "ALBERT PARDINI".lower() else None)

0                    NaN
1                    NaN
2         ALBERT PARDINI
3                    NaN
4                    NaN
               ...
148645               NaN
148647               NaN
148648               NaN
148649               NaN
148653               NaN
Name: EmployeeName, Length: 148650, dtype: str

In [59]:
data[data['EmployeeName'] == "ALBERT PARDINI"]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011

In [60]:
data[data['EmployeeName'] == "ALBERT PARDINI"]['JobTitle']

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: str

In [61]:
print(f"The Job Title for Albert Pardini is: {data[data['EmployeeName'] == 'ALBERT PARDINI']['JobTitle'].iloc[0]}")

The Job Title for Albert Pardini is: CAPTAIN III (POLICE DEPARTMENT)

**16. `How much 'ALBERT PARDINI' earned (Include Benefits)?`**

In [62]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [63]:
data['EmployeeName'] == "ALBERT PARDINI"

0         False
1         False
2          True
3         False
4         False
          ...
148645    False
148647    False
148648    False
148649    False
148653    False
Name: EmployeeName, Length: 148650, dtype: bool

In [64]:
data[data['EmployeeName'] == "ALBERT PARDINI"]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011

In [65]:
data[data['EmployeeName'] == "ALBERT PARDINI"]['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [66]:
print(f"The total earning plus benefits for Albert Pardini is: ${data[data['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits'].iloc[0]:,.2f}")

The total earning plus benefits for Albert Pardini is: $335,279.91

**17. `Display the name of the person having the highest base pay and how much is the person base pay?`**

In [67]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [68]:
data['BasePay'].max()

np.float64(319275.01)

In [69]:
data['BasePay'] == data['BasePay'].max()

0         False
1         False
2         False
3         False
4         False
          ...
148645    False
148647    False
148648    False
148649    False
148653    False
Name: BasePay, Length: 148650, dtype: bool

In [70]:
data[data['BasePay'] == data['BasePay'].max()]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
72925,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013

In [71]:
data[data['BasePay'] == data['BasePay'].max()]['EmployeeName']

72925    Gregory P Suhr
Name: EmployeeName, dtype: str

In [72]:
data[data['BasePay'] == data['BasePay'].max()]['BasePay']

72925    319275.01
Name: BasePay, dtype: float64

In [73]:
print(f"The name of the person with highest base pay is {data[data['BasePay'] == data['BasePay'].max()]['EmployeeName'].iloc[0]} and with a base pay of ${data[data['BasePay'] == data['BasePay'].max()]['BasePay'].iloc[0]:,.2f}")

The name of the person with highest base pay is Gregory P Suhr and with a base pay of $319,275.01

**18. `Find the average base pay for all employee per year`**

In [74]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [75]:
data['BasePay']

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...
148645         0.00
148647         0.00
148648         0.00
148649         0.00
148653         0.00
Name: BasePay, Length: 148650, dtype: float64

In [76]:
data['Year'].unique()

array([2011, 2012, 2013, 2014])

###### *Here, we use the groupby() method to categorize the years and average the base pay based on each year*

In [77]:
data.groupby(['Year'])['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

**19. `Find the average base pay of all employee per job title`**

In [78]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [79]:
data.groupby(['JobTitle'])['BasePay'].mean()

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                     66374.400000
                                                      ...
X-RAY LABORATORY AIDE                             47664.773077
X-Ray Laboratory Aide                             46086.387100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
Youth Comm Advisor                                39077.957500
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 2158, dtype: float64

**20. `Find the average basepay of the employee having job title ACCOUNTANT`**

In [80]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [81]:
data[data['JobTitle'] == "ACCOUNTANT"]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
19263,CARLITO NEPACENA,ACCOUNTANT,65392.01,0.0,0.00,NaN,65392.01,65392.01,2011
19324,ROSALINDA TAN,ACCOUNTANT,65225.31,0.0,0.00,NaN,65225.31,65225.31,2011
20992,NELSON ALVARADO,ACCOUNTANT,60076.24,0.0,0.00,NaN,60076.24,60076.24,2011
25927,JEANETTE COOPER,ACCOUNTANT,42522.30,0.0,2782.08,NaN,45304.38,45304.38,2011
35285,CESAR PALARCA,ACCOUNTANT,0.00,0.0,1148.40,NaN,1148.40,1148.40,2011

In [82]:
data[data['JobTitle'] == "ACCOUNTANT"]['BasePay'].mean()

np.float64(46643.172)

In [83]:
print(f"The average base pay for employee with the job title 'ACCOUNTANT' is: ${data[data['JobTitle'] == 'ACCOUNTANT']['BasePay'].mean():,.2f}")

The average base pay for employee with the job title 'ACCOUNTANT' is: $46,643.17

**21. `Find the top 5 most common jobs`**

In [84]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [85]:
data['JobTitle'].value_counts()

JobTitle
Transit Operator                  7036
Special Nurse                     4389
Registered Nurse                  3736
Public Svc Aide-Public Works      2518
Police Officer 3                  2421
                                  ...
Marina Associate Manager             1
Sr Cnselor, Juv Hall (SFERS)         1
Forensic Toxicologist Supervis       1
Conversion                           1
Cashier 3                            1
Name: count, Length: 2158, dtype: int64

In [86]:
# TOP 5 COMMON JOBS

data['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

##### THE END OF PROJECT 3